services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\AppTypes\SymfonyTwoBundle\CacheClearer\SymfonyTwoCacheClearer:
        tags:
            - {name: domainator.cacheclearer, for: DigipolisGent\Domainator9k\AppTypes\SymfonyTwoBundle\Entity\SymfonyTwoApplication}
